[project]
name = "graph_engineering"
version = "0.1.0"
description = "simple python app for pupils to understand how different graphs look and change"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]